/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.Gui;
import com.conexion.conexion;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
/**
 *
 * @author Gustavo Adolfo
 */
public class proveedor extends javax.swing.JFrame {
    conexion jCn = new conexion();
    Statement jSt;
    ResultSet jRst;
    DefaultTableModel modelo;
    /**
     * Creates new form proveedor
     */
    public proveedor() {
        initComponents();
        cargardata();
    }

    public void cargardata(){
        String Isql = "select * from proveedor";
        String [] headerdata = {"COD","NOMBRE","DIRECCION","TELEFONO","EMAIL"};
        Object [] Data = new Object[5];
        modelo = new DefaultTableModel(null,headerdata);
        try{
            jSt = jCn.connection().createStatement();
            jRst=jSt.executeQuery(Isql);
            while(jRst.next()){
                Data[0] = jRst.getString("cod_proveedor");
                Data[1] = jRst.getString("nom_pv");
                Data[2] = jRst.getString("dir_pv");
                Data[3] = jRst.getString("tel_pv");
                Data[4] = jRst.getString("email_pv");
                modelo.addRow(Data);
            }
            jtblProveedor.setModel(modelo);
        }catch(SQLException e){
            e.getMessage();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpEstructura = new javax.swing.JPanel();
        jpCuadrotexto = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtxtTelefono = new javax.swing.JTextField();
        jtxtCodigo = new javax.swing.JTextField();
        jtxtNombre = new javax.swing.JTextField();
        jtxtEmail = new javax.swing.JTextField();
        jtxtDireccion = new javax.swing.JTextField();
        jpBotones = new javax.swing.JPanel();
        jbtnNuevo = new javax.swing.JButton();
        jbtnGuardar = new javax.swing.JButton();
        jbtnActualizar = new javax.swing.JButton();
        jbtnSalir = new javax.swing.JButton();
        jbtnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblProveedor = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpEstructura.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpCuadrotexto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("EMAIL :");
        jpCuadrotexto.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel2.setText("CODIGO :");
        jpCuadrotexto.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, -1, -1));

        jLabel3.setText("NOMBRE :");
        jpCuadrotexto.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel4.setText("DIRECCION :");
        jpCuadrotexto.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel5.setText("TELEFONO :");
        jpCuadrotexto.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jtxtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTelefonoActionPerformed(evt);
            }
        });
        jpCuadrotexto.add(jtxtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 100, -1));
        jpCuadrotexto.add(jtxtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 90, -1));

        jtxtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNombreActionPerformed(evt);
            }
        });
        jpCuadrotexto.add(jtxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 320, -1));

        jtxtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtEmailActionPerformed(evt);
            }
        });
        jpCuadrotexto.add(jtxtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 320, -1));

        jtxtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDireccionActionPerformed(evt);
            }
        });
        jpCuadrotexto.add(jtxtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 320, -1));

        jpEstructura.add(jpCuadrotexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 460, 160));

        jpBotones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnNuevo.setText("NUEVO");
        jpBotones.add(jbtnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jbtnGuardar.setText("GUARDAR");
        jpBotones.add(jbtnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jbtnActualizar.setText("ACTUALIZAR");
        jbtnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnActualizarActionPerformed(evt);
            }
        });
        jpBotones.add(jbtnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jbtnSalir.setText("SALIR");
        jpBotones.add(jbtnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jbtnEliminar.setText("ELIMINAR");
        jpBotones.add(jbtnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jpEstructura.add(jpBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 140, 190));

        getContentPane().add(jpEstructura, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 630, 210));

        jtblProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblProveedor);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 620, 130));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTelefonoActionPerformed

    private void jtxtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNombreActionPerformed

    private void jtxtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtEmailActionPerformed

    private void jtxtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDireccionActionPerformed

    private void jbtnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new proveedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnActualizar;
    private javax.swing.JButton jbtnEliminar;
    private javax.swing.JButton jbtnGuardar;
    private javax.swing.JButton jbtnNuevo;
    private javax.swing.JButton jbtnSalir;
    private javax.swing.JPanel jpBotones;
    private javax.swing.JPanel jpCuadrotexto;
    private javax.swing.JPanel jpEstructura;
    private javax.swing.JTable jtblProveedor;
    private javax.swing.JTextField jtxtCodigo;
    private javax.swing.JTextField jtxtDireccion;
    private javax.swing.JTextField jtxtEmail;
    private javax.swing.JTextField jtxtNombre;
    private javax.swing.JTextField jtxtTelefono;
    // End of variables declaration//GEN-END:variables
}
